# Build script for https://github.com/tarof429/docker-react.git
sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tarof429/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tarof429/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-981150355971"
  bucket_path: "docker-react"
  on:
    branch: master
